[package]
name = "canteen"
version = "0.2.1"
authors = ["jeffdn@gmail.com"]

description = "A Flask-like microframework for Rust"
repository = "https://gitlab.com/jeffdn/rust-canteen"
readme = "README.md"
license = "MIT"

exclude = [
    '.gitlab-ci.yml',
]

[dependencies]
chrono = "0.2"
regex = "0.1"
mio = "0.5"
